SUBROUTINE CHOLDC(N,A,P)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: N
 REAL, DIMENSION(N,N), INTENT(INOUT) :: A
 REAL, DIMENSION(N), INTENT(OUT) :: P
 INTEGER :: I
 REAL :: SUMM
 DO I=1,N
   SUMM = A(I,I)- DOT_PRODUCT(A(I,1:I-1),A(I,1:I-1))
   IF (SUMM <= 0.0) THEN
     PRINT*,'ERROR IN CHOLDC'
     STOP
   ENDIF
   P(I) = SQRT(SUMM) 
   A(I+1:N,I) = (A(I,I+1:N) - MATMUL(A(I+1:N,1:I-1),A(I,1:I-1)))/P(I)
 ENDDO
END SUBROUTINE CHOLDC 
