SUBROUTINE GASDEV(HARVEST)
 IMPLICIT NONE
 REAL, INTENT(OUT) :: HARVEST
 REAL :: RSQ, V1, V2
 REAL, SAVE :: G
 LOGICAL, SAVE :: GAUS_STORED=.FALSE.
 IF (GAUS_STORED) THEN
   HARVEST = G
   GAUS_STORED=.FALSE.
 ELSE
  DO 
    CALL RANDOM_NUMBER(V1)
    CALL RANDOM_NUMBER(V2)
    V1 = 2.0*V1 - 1.0
    V2 = 2.0*V2 - 1.0
    RSQ = V1*V1 + V2*V2
    IF (RSQ > 0.0 .AND. RSQ < 1.0) EXIT
  ENDDO
  RSQ = SQRT(-2.0*LOG(RSQ)/RSQ)
  HARVEST = V1*RSQ
  G = V2*RSQ
  GAUS_STORED=.TRUE.
 ENDIF
END SUBROUTINE GASDEV
