PROGRAM MASTER
 USE SETUP
 NAMELIST/ASSIM/L_OI,L_2DVAR,L_EC,L_ENKF,L_NOISE,L_EKF,L_WG,L_2M
 READ (8,NML=ASSIM)
 REWIND (8)
 IF (.NOT.L_OI .AND. .NOT.L_EC .AND. .NOT.L_EKF .AND. .NOT.L_2DVAR .AND. .NOT.L_ENKF) THEN
   PRINT *,'NO ASSIMILATION RUN - REF or OL'      
   CALL MAIN
 ELSEIF (L_OI .OR. L_EKF .OR. L_2DVAR) THEN
   PRINT *,'ASSIMILATION RUN - OI or EKF or 2DVAR'
   CALL MAIN_OI
 ELSEIF (L_ENKF) THEN
   PRINT *,'ASSIMILATION RUN - ENKF'
   CALL MAIN_ENKF
 ELSE
   PRINT *,'WRONG SET OF OPTIONS CANNOT DO ANYTHING'
 ENDIF 
 STOP
END PROGRAM MASTER
