SUBROUTINE PRINT_OUTPUT_OI(NDIM,NSTEP,DT,T2M,RH2M,TS,T2,WG,W2,TB,H,LE,RN,G,PR,RO)
 USE CONST
 USE SURF1 
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: NDIM
 INTEGER, INTENT(IN) :: NSTEP
 REAL,    INTENT(IN) :: DT
 REAL, INTENT(IN), DIMENSION(NDIM)   :: T2M, RH2M, TS, T2, WG, W2, &
&                                       RN, H, LE, G, PR, RO
 REAL, INTENT(IN), DIMENSION(NDIM,2) :: TB
 REAL, SAVE  :: ZEV, ZPR, ZRO, ZRN, ZHS, ZGF
 REAL :: IDAY
 INTEGER :: I, IP
 IP = 1
 IDAY = (NSTEP)*DT/86400.0
 WRITE (22,100) IDAY, T2M(IP), RH2M(IP), TB(IP,1), TB(IP,2)
 WRITE (23,100) IDAY, TS(IP), T2(IP), WG(IP), W2(IP)
 WRITE (24,100) IDAY, RN(IP), H(IP),  LE(IP), G(IP)   
 IF (NSTEP == 1) THEN
   ZEV = LE(IP)/LV*DT
   ZPR = PR(IP)*DT
   ZRO = RO(IP)
   ZRN = RN(IP)/LV*DT
   ZHS = H(IP)/LV*DT 
   ZGF = G(IP)/LV*DT
 ELSE
   ZEV = ZEV + LE(IP)/LV*DT
   ZPR = ZPR + PR(IP)*DT
   ZRO = ZRO + RO(IP)
   ZRN = ZRN + RN(IP)/LV*DT
   ZHS = ZHS + H(IP)/LV*DT
   ZGF = ZGF + G(IP)/LV*DT
 ENDIF
 WRITE (25,100) IDAY, ZEV, ZPR, ZRO 
 WRITE (26,100) IDAY, ZRN, ZEV, ZHS, ZGF 
 100 FORMAT(1X,F8.5,4(1X,E15.8))
 RETURN
END SUBROUTINE PRINT_OUTPUT_OI
